### PR TITLE
Missing yml doc for intermediate performance models

### PR DESCRIPTION
**Pull request by mmmiah**
This PR address the missing model description in yml based on issue described in #283.

### CODE REVIEW

**Review by britt-allen — APPROVED** [review]
Thank you Mintu!

**Comment by britt-allen** [comment]
Can you add some docs for this one too: int_performance__station_metrics_agg_hourly [model](https://california.getdbt.com/accounts/6/develop/3012/docs/index.html#!/model/model.caldata_mdsa_caltrans_pems.int_performance__station_metrics_agg_hourly)

Then we can get this merged!

**Comment by mmmiah** [comment]
Closed as completed

**Comment by britt-allen** [comment]
My comment was a few seconds too late, you can add docs for the remaining one in a new PR.

**Comment by mmmiah** [comment]
I think that the model description is already there
image

**Comment by britt-allen** [comment]
Oh nice catch, thank you!

**Pull request merged**
