### PR TITLE
Ten days corridor level performance mart model bug fixing

### PR DESCRIPTION
**Pull request by mmmiah**
There was bugs in logic that generate just 10 days back single day data, while our target was getting recent all 10 days data. it seems the data size is too big, I am limiting this data for just a single recent week

### CODE REVIEW

**Comment by mmmiah** [comment]
@kengodleskidot , this is ready for re-review my edits

**Review by kengodleskidot — COMMENTED** [review]
On line 133 I believe you included vht into a calculation that should use vmt, see screenshot below. Also is there a yaml file or comments you can include about this model  that describe what the penetration values represent and the level of comparison being made? It looks like an average per lane comparison based on the calculations. A description of what acceptable values would be (possibly a range) or other context would help others in understanding what this analysis represents.

image

**Comment by mmmiah** [comment]
> On line 133 I believe you included vht into a calculation that should use vmt, see screenshot below. Also is there a yaml file or comments you can include about this model that describe what the penetration values represent and the level of comparison being made? It looks like an average per lane comparison based on the calculations. A description of what acceptable values would be (possibly a range) or other context would help others in understanding what this analysis represents.
> 
> image

Great catch! I just fixed it and also added yml file!

**Review by kengodleskidot — APPROVED** [review]
@mmmiah looks good to go!

**Comment by mmmiah** [comment]
closed as completed

**Pull request merged**
