### PR TITLE
Too few samples

### LINKED ISSUE #79: PeMS detector health diagnostics: too few data samples
Implement Test number 2 from the [PeMS User Guide](https://pems.dot.ca.gov/Papers/PeMS_Intro_User_Guide_v6.pdf):

image

**Data sources**: 30 second raw data, VDS metadata (controller, station, detector)

### PR DESCRIPTION
**Pull request by britt-allen**
This code is selecting all instances of too few samples per lane, for now lane 7 and lane 8 are not being included as they cause the query to produce unknown results. This will require further understanding of the data and/or investigation. This closes #79.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Does this supersede #96

**Comment by britt-allen** [comment]
> Does this supersede #96

Nope, it adds a model. I relied on a model built in Ken's branch to build this one.

**Comment by ian-r-rose** [comment]
> > Does this supersede #96
> 
> Nope, it adds a model. I relied on a model built in Ken's branch to build this one.

Did you intend to make this PR against Ken's then? What is your plan for merging these?

**Comment by britt-allen** [comment]
> > > Does this supersede #96
> > 
> > 
> > Nope, it adds a model. I relied on a model built in Ken's branch to build this one.
> 
> Did you intend to make this PR against Ken's then? What is your plan for merging these?

I did intend to! My plan is to merge this model into his branch since it has dependencies with work in his branch and then when his branch gets approved it will all be in main.

**Comment by ian-r-rose** [comment]
Do you want to re-open against his branch then?

**Pull request closed without merging**
