### PR TITLE
Imputation for local and regional averages

### PR DESCRIPTION
**Pull request by ian-r-rose**
Work-in-progress towards #272. The idea here is to just string along another aggregate where we are already doing aggregation using the median of the local/regional regressions. This aggregate is just the average of local/regional station data.

As of now, this isn't quite having the performance characteristics I would want (it's considerably slower than I expected), and I haven't had the chance to figure out why.

### CODE REVIEW

**Comment by jkarpen** [comment]
Adding @mmmiah as I believe the plan was for him to take this over when Ian went out but we will confirm in sprint planning call.

**Comment by mmmiah** [comment]
@JamesSLogan , I think that it is read for your review. I did some corrections on 'data not required imputation'. I found that there was overlap between data needs imputation and data not need imputation. Thank you!

**Comment by JamesSLogan** [comment]
> @britt-allen , Could you please see what is falling the dbt CI test. I have tried to delete the corresponding PR, but still same error

Taking a look!

**Review by JamesSLogan — APPROVED** [review]
Looks good @mmmiah , thanks for taking care of this. fyi a retry (from start) helped CI pass in this instance.

**Pull request merged**
