### PR TITLE
Adding terraform updates for sentinel service user - CALTRANS

### PR DESCRIPTION
**Pull request by melanie-logan**
Updated Terraform config, using the latest data-infrastructure updates, to add Sentinel service user accounts to Snowflake.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Looks like this needs bumps in the tf version and terraform lock files

**Comment by ian-r-rose** [comment]
CI still isn't passing, I suspect because of [this](https://cagov.github.io/data-infrastructure/cloud-infrastructure/#updating-terraform-dependencies)

**Comment by melanie-logan** [comment]
> CI still isn't passing, I suspect because of [this](https://cagov.github.io/data-infrastructure/cloud-infrastructure/#updating-terraform-dependencies)

Thanks, hopefully that did it!

**Comment by ian-r-rose** [comment]
Can you also update the lockfile for the prod environment?

**Comment by melanie-logan** [comment]
> Can you also update the lockfile for the prod environment?

I just confirmed the prd lock file is updated, but there are no changes to stage. I think I updated the prd lock file originally and not dev.

**Comment by ian-r-rose** [comment]
> > Can you also update the lockfile for the prod environment?
> 
> I just confirmed the prd lock file is updated, but there are no changes to stage. I think I updated the prd lock file originally and not dev.

Interesting, I expected a change to the git ref to require a change to the lockfile, but maybe it just hashes the contents, so if there were no changes to the source module there are no lockfile updates?

**Review by ian-r-rose — APPROVED** [review]
Thanks @melanie-logan!

**Pull request merged**
