### PR TITLE
Summer versionless test

### PR DESCRIPTION
**Pull request by summer-mothwood**
changes will not be merged

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I wouldn't expect this to work until the nightly job has run, as I think the changes need to also be reflected in the manifest to which we are comparing

**Comment by summer-mothwood** [comment]
Same! Just capturing some metrics / logs on a specific change pre-nightly build to compare against! From: Ian Rose ***@***.***>Date: Wednesday, December 4, 2024 at 4:08 PMTo: cagov/caldata-mdsa-caltrans-pems ***@***.***>Cc: summer-mothwood ***@***.***>, Author ***@***.***>Subject: Re: [cagov/caldata-mdsa-caltrans-pems] Summer versionless test (PR #493)I wouldn't expect this to work until the nightly job has run, as I think the changes need to also be reflected in the manifest to which we are comparing—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ian-r-rose** [comment]
Roger, carry on!

**Comment by summer-mothwood** [comment]
captured CI runtime and logs for comparison. closing without merge!

**Pull request closed without merging**
