### PR TITLE
created the bottlenecks doc file

### LINKED ISSUE #295: Document Bottlenecks
Information about this is scattered across issues, PRs, comments within models, and dbt docs. Synthesizing this in narrative form could be helpful for future and current team members to reference.

### PR DESCRIPTION
**Pull request by britt-allen**
closes #295

### CODE REVIEW

**Comment by britt-allen** [comment]
I am currently stuck on #255/#306 so I am taking a pause to write out all that I've learned about bottlenecks in hopes that it'll unstick me and provide a clear path forward. Regardless, the current definitions and logic needs to be centralized in one place

**Comment by britt-allen** [comment]
This is ready for review and merge barring any requests for changes. The idea is that this is just a start and this doc will evolve as others feel the need to contribute to it.

**Review by thehanggit — APPROVED** [review]
Looks good to me! Thank you @britt-allen

**Review by mmmiah — APPROVED** [review]
Great documentation with figures and explanations! Looks good to me!

**Comment by britt-allen** [comment]
Thanks for the review y'all!

**Pull request merged**
