### PR TITLE
Consolidation of local and regional regression

### PR DESCRIPTION
**Pull request by mmmiah**
This PR consolidate the local and regional regression estimates together based on issue #240. The join is done in a incremental form to avoid large joining over historical time period.

### CODE REVIEW

**Comment by mmmiah** [comment]
@ian-r-rose , any ideas why git pre-commit check is not happening here? Thank you!

**Comment by ian-r-rose** [comment]
> @ian-r-rose , any ideas why git pre-commit check is not happening here? Thank you!

Good question, I'm not sure! Let's see if it persists, it may just be a glitch in github

**Review by ian-r-rose — COMMENTED** [review]
Thanks @mmmiah, I was hoping that the local and regional versions of the regressions were similar enough that they could actually be combined into _the same file_, where the final table just has columns for both local and regional regressions. So we would actually get one fewer model, as they are both combined into `int_imputation__detector_agg_five_minutes_local_regional`.

If it's doable, that could save us a significant amount of effort in not needing to do as many large-to-large joins. Does that make sense?

**Comment by mmmiah** [comment]
> Thanks @mmmiah, I was hoping that the local and regional versions of the regressions were similar enough that they could actually be combined into _the same file_, where the final table just has columns for both local and regional regressions. So we would actually get one fewer model, as they are both combined into `int_imputation__detector_agg_five_minutes_local_regional`.
> 
> If it's doable, that could save us a significant amount of effort in not needing to do as many large-to-large joins. Does that make sense?

I think that it is doable, let me try. I will kill this PR then Once I am done with that. Making this PR as draft, no need to review anymore

**Comment by mmmiah** [comment]
Did this consolidation within the local regression

**Pull request closed without merging**
