### PR TITLE
update imputation upstream model

### PR DESCRIPTION
**Pull request by mmmiah**
Recently we developed one more imputation model known as average local_regional model #360, therefore we need to incorporate this changes in all upstream imputation model. I have updated the logic of imputation as well as ymal file for the documentation. This PR is related to the issue #367

### CODE REVIEW

**Comment by mmmiah** [comment]
@JamesSLogan , Could you please also check this one dbt CI failing issue. Thanks!

**Comment by JamesSLogan** [comment]
> @JamesSLogan , Could you please also check this one dbt CI failing issue. Thanks!

@mmmiah , snowflake is giving an error since it can't find `VOLUME_LOCAL_AVG` - it looks like this column isn't available to the model, at least in its current state. Now that #360 is merged, you should be able to **pull main into this feature branch** to get that new column.

**Comment by mmmiah** [comment]
@JamesSLogan , this one passed the dbt CI, all checks look good!  James, Could you please review this PR? Thanks!

**Review by JamesSLogan — APPROVED** [review]
Thanks Mintu, look good to me. This area of code might be a good candidate for adding some macros in the future.

**Pull request merged**
